name: Maven Build

on:
  push:
    branches:
      - 'wip/**'
  pull_request:
    branches: [ "master" ]
  merge_group:
    types: [checks_requested]

jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        java: [ 8, 11 ]
        experimental: [false]
        include:
          - java: 17
            experimental: true
    steps:
    - uses: actions/checkout@v3
    - name: Prevent wip merge
      if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'wip/')
      run: |
        echo "::error::WIP branches cannot be merged"
        exit 1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --no-transfer-progress --batch-mode package --file pom.xml
