name: Maven deploy release
on:
  push:
    branches: [ "release/*" ]
jobs:
  publish:
    # Avoid loops
    if: github.event.commits[0].author.email != 'actions-bot@github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Split branch into release version
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=fragment::${BRANCH##*/}"

      - name: Configure git user
        run: |
          git config user.email "actions-bot@github.com"
          git config user.name "GitHub Actions (run by ${{ github.actor }})"

      - name: Maven set release version
        run: |
          mvn --no-transfer-progress versions:set -DoldVersion=\* -DnewVersion=${{ steps.split.outputs.fragment }} -DgroupId=org.jmock -DgenerateBackupPoms=false
          git add .
          git commit --no-edit -m "Release version ${{ steps.split.outputs.fragment }}"
          git tag -a -m "Release version ${{ steps.split.outputs.fragment }}" ${{ steps.split.outputs.fragment }}
          mvn versions:set -DoldVersion=* -DnextSnapshot=true -DgroupId=org.jmock -DgenerateBackupPoms=false
          git checkout -b ${{ github.ref_name }}-snapshot
          git add .
          git commit --no-edit -m "Open development for next release"
          git push origin ${{ github.ref_name }} HEAD --tags
          gh pr create -B ${{ github.ref_name }} --title 'Merge release back into master' --body 'Created by Github action'
